name: Test my Lib

on:
  push:
    branches: [main]


jobs:
  build:
    runs-on: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.8.0
      with:
        # Optional SDK version to use. If not provided, will install global.json version when available. Examples: 2.2.104, 3.1, 3.1.x
        dotnet-version: net5.0 # optional
    - name: Do the tests
      run: |
        cd test\MyTest
        dotnet test
    
